kind: Secret
apiVersion: v1
metadata:
  name: blog-django-py-generic-webhook-secret
  namespace: group001_fiap
  selfLink: /api/v1/namespaces/group001_fiap/secrets/blog-django-py-generic-webhook-secret
data:
  WebHookSecretKey: ZWZlMjc3OGUwMDU3Nzc3OA==
type: Opaque
