kind: Secret
apiVersion: v1
metadata:
  name: blog-django-py-github-webhook-secret
  namespace: group001_fiap
  selfLink: /api/v1/namespaces/group001_fiap/secrets/blog-django-py-github-webhook-secret
data:
  WebHookSecretKey: ZWJiM2NhZTA2ZmEyZTY4MA==
type: Opaque