apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blog-django-py
  namespace: group001-fiap
  selfLink: /apis/image.openshift.io/v1/namespaces/fiap-test/imagestreams/blog-django-py
labels:
    app: blog-django-py
    app.kubernetes.io/component: blog-django-py
    app.kubernetes.io/instance: blog-django-py
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-django-py-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  lookupPolicy:
    local: false

