kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: plugin-k8s-role-binding
subjects:
- kind: ServiceAccount
  name: wauser
roleRef:
  kind: Role
  name: k8s-role
  apiGroup: rbac.authorization.k8s.io